# Generated by Django 3.2.3 on 2021-06-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
