# Generated by Django 3.2.3 on 2021-06-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0011_auto_20210608_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koszyk_przedmioty',
            name='cena_razem',
        ),
    ]
