# Generated by Django 3.2.3 on 2021-06-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0012_remove_koszyk_przedmioty_cena_razem'),
    ]

    operations = [
        migrations.AddField(
            model_name='koszyk_przedmioty',
            name='kosz_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.profil'),
        ),
    ]
