# Generated by Django 3.2.3 on 2021-06-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0013_koszyk_przedmioty_kosz_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koszyk_przedmioty',
            name='kosz_profil',
        ),
    ]
