# Generated by Django 3.2.3 on 2021-06-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produkty', '0014_remove_koszyk_przedmioty_kosz_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koszyk_przedmioty',
            options={'verbose_name': 'Koszyk_Przedmiot', 'verbose_name_plural': 'Koszyk_Przedmioty'},
        ),
        migrations.RemoveField(
            model_name='koszyk',
            name='kosz_profil',
        ),
        migrations.AddField(
            model_name='koszyk',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
