# Generated by Django 3.2.3 on 2021-06-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0017_auto_20210608_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koszyk_przedmioty',
            options={},
        ),
        migrations.RemoveField(
            model_name='koszyk',
            name='user',
        ),
        migrations.AddField(
            model_name='koszyk',
            name='kosz_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.profil'),
        ),
        migrations.AddField(
            model_name='koszyk_przedmioty',
            name='kosz_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.profil'),
        ),
    ]
