# Generated by Django 3.2.3 on 2021-06-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0018_auto_20210608_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koszyk_przedmioty',
            name='kosz_profil',
        ),
    ]
