# Generated by Django 3.2.3 on 2021-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0020_auto_20210608_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
