# Generated by Django 3.2.3 on 2021-06-09 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produkty', '0023_alter_historia_zakupów_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_zakupów',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
