# Generated by Django 3.2.3 on 2021-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0025_produkty_zdjęcie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='zdjęcie',
            field=models.ImageField(blank=True, default=None, height_field=200, max_length=20, null=True, upload_to='', width_field=200),
        ),
    ]
