# Generated by Django 3.2.3 on 2021-06-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0026_alter_produkty_zdjęcie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_zakupów',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produkty.koszyk'),
        ),
    ]
